# Generated by Django 6.0.3 on 2026-04-22 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='media/category/Снимок_экрана_2026-03-29_14-53-20.png', upload_to='accounts/', verbose_name='ава')),
                ('bio', models.TextField(blank=True, verbose_name='о себе')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город пользовталея')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='День рождение пользователя')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
