# Generated by Django 6.0.3 on 2026-04-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(blank=True, max_length=100, verbose_name='Категория товаров')),
                ('shop_name', models.CharField(blank=True, max_length=100, verbose_name='Название магазина')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='accounts.profile', verbose_name='Продовец')),
            ],
        ),
    ]
