# Generated by Django 6.0.3 on 2026-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_approved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
