# Generated by Django 6.0.3 on 2026-04-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
