# Generated by Django 6.0.3 on 2026-04-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_seller_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='user',
            new_name='profile',
        ),
    ]
