# Generated by Django 6.0.3 on 2026-05-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_seller_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
