# Generated by Django 6.0.3 on 2026-05-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_seller_is_approved'),
        ('catalog', '0004_alter_product_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
