# Generated by Django 6.0.3 on 2026-05-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_seller_product_category'),
        ('catalog', '0004_alter_product_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='product_category',
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='accounts.profile', verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='seller',
            name='product_category',
            field=models.ManyToManyField(blank=True, related_name='sellers', to='catalog.category'),
        ),
    ]
