# Generated by Django 6.0.3 on 2026-05-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_author',
            field=models.CharField(default=1, max_length=100, verbose_name='Продавец'),
            preserve_default=False,
        ),
    ]
