# Generated by Django 6.0.3 on 2026-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_author',
            field=models.CharField(max_length=100, null=True, verbose_name='Продавец'),
        ),
    ]
