# Generated by Django 6.0.3 on 2026-05-13 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_seller_product_category_alter_seller_profile_and_more'),
        ('catalog', '0004_alter_product_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_author',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.seller'),
            preserve_default=False,
        ),
    ]
